FROM node:18-alpine AS base

WORKDIR /app


RUN apk add --no-cache git openssh-client

RUN git clone https://vladislavkovaliov@github.com/wi-untitled/strapi-cloud-template-blog-b0af461fdc.git .

RUN git checkout docker/setup

RUN npm config set fetch-retry-maxtimeout 600000 -g && npm install && npm install pg --save

RUN npm run build

RUN ["npm", "run", "build"]
EXPOSE 1337
CMD ["npm", "run", "develop"]
