version: "3"
services:
  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: always
    env_file: ./.env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./pg-data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
    networks:
      - strapi

  strapi:
    container_name: strapi
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile_strapi
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      PUBLIC_URL: ${PUBLIC_URL}
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: ${APP_KEYS}
      API_TOKEN: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./.env:/app/.env
      - ./public/uploads:/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi

  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nextjs:latest
    restart: always
    env_file: ./.env
    environment:
      # TODO: when the project is done
      #       NEXT_STRAPI_API need to be changed on strapi
      #       to make request into docker container's strapi
      #
      #       IMPORTANT! Now NEXT_STRAPI_API is CLOUD HOST
      NEXT_STRAPI_API: ${NEXT_STRAPI_API}
      NEXT_PUBLIC_RECAPTCHA_KEY: ${NEXT_PUBLIC_RECAPTCHA_KEY}
      NEXT_PRIVATE_RECAPTCHA_SECRET_KEY: ${NEXT_PRIVATE_RECAPTCHA_SECRET_KEY}
      NEXT_SENDGRID_API_KEY: ${NEXT_SENDGRID_API_KEY}
    ports:
      - "3000:3000"
    networks:
      - strapi
    depends_on:
      - strapi
      - strapiDB

  nginx:
    image: nginx:1-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8089:80"
    networks:
      - strapi
    depends_on:
      - strapi
      - nextjs

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
