version: "3"
services:
  nextjs:
    container_name: nextjs
    build:
      context: ./packages/nextjs
      dockerfile: ./Dockerfile
    image: nextjs:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      # TODO: when the project is done
      #       NEXT_STRAPI_API need to be changed on strapi
      #       to make request into docker container's strapi
      #
      #       IMPORTANT! Now NEXT_STRAPI_API is CLOUD HOST
      NEXT_STRAPI_API: ${NEXT_STRAPI_API}
      NEXT_PUBLIC_RECAPTCHA_KEY: ${NEXT_PUBLIC_RECAPTCHA_KEY}
      NEXT_PRIVATE_RECAPTCHA_SECRET_KEY: ${NEXT_PRIVATE_RECAPTCHA_SECRET_KEY}
      NEXT_SENDGRID_API_KEY: ${NEXT_SENDGRID_API_KEY}
    ports:
      - "3000:3000"
    networks:
      - strapi
    depends_on:
      - strapi

  strapi:
    container_name: strapi
    build:
      context: ./packages/strapi
      dockerfile: ./Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./packages/strapi/config:/opt/app/config
      - ./packages/strapi/src:/opt/app/src
      - ./packages/strapi/package.json:/opt/package.json
      - ./.env:/opt/app/.env
      - ./packages/strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./.env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./pg-data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
